### ISSUE TITLE
move video, add content and call to action button

### ISSUE THREAD

**Issue by wuh0o** [CodeForPhilly/cfp-mockup#20]
- 2 columns, video on left side, content on right side
 - content should be context for call to action button
 - call to action button that links to volunteer page
 - add border

**Comment by bld2104** [comment]
Ignore border for now, expand video so that it goes all the way to the left of browser and to header on the top. On the right side, it should cut off with enough space for content and button. On the bottom it should cut off about where it is now. 

Content: Contribute towards technology-related projects that benefit the City of Philadelphia. No coding experience required.

Button: Volunteer and links to here: https://codeforphilly.github.io/cfp-mockup/volunteer.html
