### ISSUE TITLE
Edit CSS for the header

### ISSUE THREAD

**Issue by bld2104** [CodeForPhilly/cfp-mockup#27]
Search bar either needs to be moved somewhere else or use a collapsible search bar that only expands when clicked (like a magnifying glass icon that expands when clicked).

**Comment by ZacharyRSmith** [comment]
Reopening because we had to revert the PR that closed this issue because the PR accidentally had a commit not meant to be merged.

However, maybe we no longer need to change the header: with the change of "Community/Connect" to "Slack (Chat)", the search bar always has enough room.

If we still want to collapse the navbar into a hamburger menu sooner, it's an easy 1-line change.

But personally, I prefer collapsing as late as possible.
